sensor:
  - platform: atlas_scientific
#    port: /dev/ttyUSB0
    port: /dev/ttyAMA0
#    scan_interval: 60
    scan_interval: 31536000
#    scan_interval: 10

  - platform: statistics
    name: ph
    entity_id: sensor.ezo_ph
    max_age:
      minutes: 10
    # precision: 3

input_number:
  ph_target:
    min: 6.5
    max: 8.5
    step: 0.01
    unit_of_measurement: 'pH'
    icon: mdi:alpha-h-circle-outline
    mode: box

automation:
- alias: ph_start
  id: '1559669855764'
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.ph
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.pump
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.ph

- alias: ph_high
  id: '1559049859759'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.ph_mean
    above: 7.5
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}{{-
        "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'pH high ({{trigger.to_state.state}})!!!'
    service: notify.pushbullet

- alias: ph_low
  id: '1559049839760'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.ph_mean
    below: 6.9
    for:
      hours: 48
  condition: []
  action:
  - data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}{{-
        "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'pH low ({{trigger.to_state.state}})!!!'
    service: notify.pushbullet

- alias: ph_bad
  id: '1559049893756'
  initial_state: true
  trigger:
  - platform: template
    value_template: '{{state_attr("sensor.ph_mean", "standard_deviation") > 0.1}}'
  condition: []
  action:
  - service: notify.pushbullet
    data_template:
      message: '{{trigger.to_state.attributes.friendly_name}}: {{trigger.to_state.state}}{{-
        "\n\n" -}}@{{now().strftime("%H:%M")}}[{{now().day}}/{{now().month}}]'
      title: 'pH probe bad (calibrate?) !!!'
  - service: automation.turn_off
    entity_id: automation.ph_bad

- alias: ph_target
  id: '1559146893656'
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_number.ph_target
  condition: []
  action:
    - service: automation.trigger
      entity_id: automation.muriatic_set
  
